version: '3.7'

services:
  nginx:
    image: nginx:1.25.1-alpine
    ports:
      - '${NGINX_PORT:-80}:80'
    environment:
      - NGINX_APP_HOST
    volumes:
      - ./app:/app/
      - ./docker/nginx/${APP_ENV}_templates/templates:/etc/nginx/templates
    networks:
      - net
    depends_on:
      - php-fpm
      - mercure

  php-fpm:
    build: ./docker/php/dev/context
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "${UID}:${GID}"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./app:/app/
      - ./docker/php/dev/php-fpm.php.ini:/usr/local/etc/php/conf.d/docker-php-limit.ini
      - ./docker/php/dev/docker-xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - net
    links:
      - postgres

  postgres:
    image: postgres:16.2-alpine
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    networks:
      - net

  mercure:
    image: dunglas/mercure
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    ports:
      - "${MERCURE_PORT:-8010}:80"
    networks:
      - net

volumes:
  mercure_data:
  mercure_config:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${NETWORK_SUBNET:-192.168.10.0/24}"
          gateway: "${NETWORK_GATEWAY:-192.168.10.1}"
  web:
    external: true
    name: rm_net
